/**
 * Work out what removing YodaMan would delete — without deleting anything.
 *
 * A privacy-first tool has to be removable. "Your code never leaves the
 * machine" is a weaker promise if a user cannot tell what YodaMan left ON the
 * machine, so `UPGRADING.md` documents the footprint and this makes it
 * executable.
 *
 * WHY PLANNING IS SEPARATE FROM DELETING.
 *
 * This module never removes a file. It returns a description, and the CLI
 * prints it; deletion is a separate, explicit step behind `--yes`. That split
 * is what makes dry-run the default rather than a flag people forget, and it is
 * what makes this testable — the interesting assertions are about what the plan
 * REFUSES to include, and they can run without a filesystem full of fixtures.
 *
 * THE RULES IT ENFORCES.
 *
 * 1. Only names in `shared/generatedPaths.js` are ever proposed. Not a glob,
 *    not "anything starting with .yodaman" — an exact allowlist.
 * 2. `openspec/` is never proposed. Those are the user's own specs, and they
 *    exist nowhere else.
 * 3. Nothing outside a known workspace or the home state directory is
 *    proposed, so a corrupted config cannot aim this at `/`.
 * 4. Source code is never proposed. YodaMan writes to its generated
 *    directories and to files approved through the approval gate; neither
 *    makes a user's repository ours to delete.
 */
const fs = require('fs');
const os = require('os');
const path = require('path');

const {
    GENERATED_WORKSPACE_DIRS,
    HOME_STATE_DIR,
    INSTALL_DIR_STATE,
    isUserOwned
} = require('../../shared/generatedPaths');

/**
 * Paths that must never be proposed for deletion regardless of what a config
 * claims. A workspace recorded as "/" or "~" is a corrupted config, not an
 * instruction.
 */
function isDangerousRoot(target, homeDir = os.homedir()) {
    // homeDir is a parameter, not a call to os.homedir() inside the body. The
    // first version read the real home directly, which meant the check could
    // not be exercised against a fixture at all — it silently answered
    // questions about the machine running the tests rather than about the
    // input. A guard that cannot be tested is a guard nobody has checked.
    const resolved = path.resolve(target);
    const home = path.resolve(homeDir);

    if (resolved === path.parse(resolved).root) return true;
    if (resolved === home) return true;

    // One level below home (~/Documents) is still far too broad to be a
    // workspace we generated into — except our own state directory.
    if (path.dirname(resolved) === home) {
        return path.basename(resolved) !== HOME_STATE_DIR;
    }
    return false;
}

/**
 * Build the removal plan.
 *
 * @param {object}   options
 * @param {string[]} options.workspaces  Absolute paths from config.watchedDirectories.
 * @param {string}   options.homeDir     Defaults to os.homedir().
 * @param {function} options.exists      Injectable for tests; defaults to fs.existsSync.
 * @param {string}   options.platform    Defaults to process.platform.
 * @returns {{remove: object[], protected: object[], manual: object[], skipped: object[]}}
 */
function buildUninstallPlan({
    workspaces = [],
    homeDir = os.homedir(),
    exists = fs.existsSync,
    platform = process.platform
} = {}) {
    const remove = [];
    const protectedPaths = [];
    const manual = [];
    const skipped = [];

    // Home state: logs and runtime scratch.
    const homeState = path.join(homeDir, HOME_STATE_DIR);
    if (exists(homeState)) {
        remove.push({ path: homeState, what: 'Runtime logs and state' });
    }

    for (const workspace of workspaces) {
        if (typeof workspace !== 'string' || !workspace.trim()) {
            skipped.push({ path: String(workspace), why: 'not a usable path' });
            continue;
        }
        if (isDangerousRoot(workspace, homeDir)) {
            // Loudly, not silently: a config that names "/" is a bug worth
            // seeing, and silently dropping it hides the bug.
            skipped.push({ path: workspace, why: 'too broad to be a workspace — refusing' });
            continue;
        }

        for (const dir of GENERATED_WORKSPACE_DIRS) {
            const target = path.join(workspace, dir);
            if (exists(target)) remove.push({ path: target, what: `Generated by YodaMan in ${path.basename(workspace)}` });
        }

        // Reported so the user can see it was considered and deliberately kept.
        const specs = path.join(workspace, 'openspec');
        if (exists(specs)) {
            protectedPaths.push({ path: specs, why: 'your specs — YodaMan only ever reads these' });
        }
    }

    // Things a user must do themselves, because they are not ours to run.
    manual.push({
        action: 'npm uninstall -g yodaman',
        why: `removes the program and its own state (${INSTALL_DIR_STATE.join(', ')})`
    });
    manual.push({
        action: 'Remove the "yodaman" entry from any MCP client config',
        why: 'see docs/guides/mcp.md for where each client keeps it'
    });

    if (platform === 'darwin') {
        const plistBackup = path.join(
            homeDir, 'Library', 'LaunchAgents', 'homebrew.mxcl.ollama.plist.yodaman-backup'
        );
        if (exists(plistBackup)) {
            // Not deleted: it is the ONLY copy of the user's original Ollama
            // service definition. Restoring it is a decision, not cleanup.
            manual.push({
                action: `Restore ${plistBackup}`,
                why: 'your original Ollama service config, saved before YodaMan changed the context length'
            });
        }
    }

    return { remove, protected: protectedPaths, manual, skipped };
}

/** Human-readable plan. Dry-run and the real run print exactly this. */
function formatUninstallPlan(plan) {
    const lines = [];

    if (plan.remove.length) {
        lines.push('Would remove:');
        for (const item of plan.remove) lines.push(`  ${item.path}\n      ${item.what}`);
        lines.push('');
    } else {
        lines.push('Nothing generated by YodaMan was found on this machine.\n');
    }

    if (plan.protected.length) {
        lines.push('Kept — yours, not YodaMan\'s:');
        for (const item of plan.protected) lines.push(`  ${item.path}\n      ${item.why}`);
        lines.push('');
    }

    if (plan.skipped.length) {
        lines.push('Skipped:');
        for (const item of plan.skipped) lines.push(`  ${item.path} — ${item.why}`);
        lines.push('');
    }

    if (plan.manual.length) {
        lines.push('You will need to do these yourself:');
        for (const item of plan.manual) lines.push(`  ${item.action}\n      ${item.why}`);
        lines.push('');
    }

    lines.push('Your source code is never touched.');
    return lines.join('\n');
}

module.exports = { buildUninstallPlan, formatUninstallPlan, isDangerousRoot, isUserOwned };
